"""Getting text off a page, by whichever route the page allows.

Most invoices that arrive by email are generated by accounting software and
carry a text layer. Reading that layer is instant and perfectly accurate, so
running OCR on them would be slower *and* worse. OCR is the fallback for pages
that are genuinely just pictures of paper.

Which route was taken is recorded on the resulting :class:`Page`, because it
changes how much the text can be trusted -- see the match-strategy tightening in
:mod:`pdf_ocr.core.score`.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pymupdf

from pdf_ocr.core.ocr.base import OcrEngine
from pdf_ocr.core.types import Page, Source, TextBlock

logger = logging.getLogger(__name__)

MIN_TEXT_LAYER_CHARS = 50
"""Below this, a page's text layer is treated as absent.

Scanned PDFs are not always empty of text: a covering letter, a stamp, or a
header added by a scanning appliance can leave a handful of characters behind.
Falling back to OCR on the strength of a dozen stray characters is what this
threshold prevents.
"""

DEFAULT_DPI = 300
"""Rendering resolution for OCR. Below roughly 200 the recognition of small
Japanese type degrades sharply; above 300 the extra pixels cost time without
buying accuracy."""


class ExtractionError(RuntimeError):
    """A PDF could not be read at all."""


def text_layer_blocks(page: pymupdf.Page) -> list[TextBlock]:
    """Blocks from the page's own text layer, one per line."""
    blocks: list[TextBlock] = []
    for block in page.get_text("dict")["blocks"]:
        if block.get("type") != 0:  # 0 is text; 1 is an embedded image
            continue
        for line in block.get("lines", []):
            text = "".join(span.get("text", "") for span in line.get("spans", []))
            if not text.strip():
                continue
            x0, y0, x1, y1 = line["bbox"]
            blocks.append(TextBlock(text=text, bbox=(x0, y0, x1, y1)))
    return blocks


def has_usable_text_layer(
    blocks: list[TextBlock], min_chars: int = MIN_TEXT_LAYER_CHARS
) -> bool:
    """Whether the text layer holds enough to classify from."""
    return sum(len(block.text.strip()) for block in blocks) >= min_chars


def render(page: pymupdf.Page, dpi: int = DEFAULT_DPI) -> tuple[np.ndarray, float]:
    """Rasterise a page, returning the image and the pixels-per-point scale."""
    pixmap = page.get_pixmap(dpi=dpi, alpha=False)
    image = np.frombuffer(pixmap.samples, dtype=np.uint8).reshape(
        pixmap.height, pixmap.width, pixmap.n
    )
    # Derived from the actual pixmap rather than assumed from the DPI, so that a
    # page with an unusual crop box still maps back correctly.
    scale = pixmap.width / page.rect.width
    return image, scale


def _to_page_coordinates(blocks: list[TextBlock], scale: float) -> list[TextBlock]:
    """Convert pixel-space OCR boxes into PDF points.

    Without this the top-quarter rules would compare pixel coordinates against a
    cutoff measured in points and would effectively never fire.
    """
    return [
        TextBlock(
            text=block.text,
            bbox=(
                block.bbox[0] / scale,
                block.bbox[1] / scale,
                block.bbox[2] / scale,
                block.bbox[3] / scale,
            ),
            confidence=block.confidence,
        )
        for block in blocks
    ]


def extract_page(
    page: pymupdf.Page,
    engine: OcrEngine | None = None,
    dpi: int = DEFAULT_DPI,
    min_chars: int = MIN_TEXT_LAYER_CHARS,
    force_ocr: bool = False,
) -> Page:
    """Extract one page, using OCR only if the text layer cannot serve.

    ``force_ocr`` exists for the debug GUI, where being able to see what the
    recogniser makes of a page that *does* have a text layer is how the two are
    compared.
    """
    blocks = [] if force_ocr else text_layer_blocks(page)
    source = Source.TEXT_LAYER

    if force_ocr or not has_usable_text_layer(blocks, min_chars):
        if engine is None:
            # Deliberately not an error: a text-layer-only run is a legitimate
            # mode, and the caller gets an empty page it can act on.
            logger.warning(
                "page %d has no usable text layer and no OCR engine was supplied",
                page.number + 1,
            )
            blocks = []
        else:
            image, scale = render(page, dpi)
            blocks = _to_page_coordinates(engine.read(image), scale)
        source = Source.OCR

    return Page(
        number=page.number + 1,
        width=page.rect.width,
        height=page.rect.height,
        blocks=blocks,
        source=source,
    )


def extract_first_page(
    path: str | Path,
    engine: OcrEngine | None = None,
    dpi: int = DEFAULT_DPI,
    min_chars: int = MIN_TEXT_LAYER_CHARS,
    force_ocr: bool = False,
) -> Page:
    """Extract the first page of a PDF.

    Only the first page, because that is where a document says what it is. On a
    scanned document every extra page costs seconds of OCR to tell us something
    the title already did.
    """
    path = Path(path)
    try:
        document = pymupdf.open(path)
    except Exception as error:  # pymupdf raises a variety of types
        raise ExtractionError(f"{path}: cannot be opened ({error})") from error

    with document:
        if document.needs_pass:
            raise ExtractionError(f"{path}: is password protected")
        if document.page_count == 0:
            raise ExtractionError(f"{path}: has no pages")
        return extract_page(document[0], engine, dpi, min_chars, force_ocr)
